version: '3.5'


services:
  testng-selenoid-ui:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      StartRemote: "yes"
    command: mvn clean test -Dgrid-url=http://selenoid:4444/wd/hub
    container_name: testng-selenoid-ui
    ports:
      - 5555:5555
    networks:
      - app


networks:
  app:
    external: true
    name: selenoid-net


