version: '3.5'
networks:
  selenoid-net:

services:
  testng-selenoid-ui:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      StartRemote: "yes"
    command: mvn clean test
    container_name: testng-selenoid-ui
    ports:
      - 0.0.0.0:5555:5555
    networks:
      - selenoid-net
