version: '3'
services:
  selenoid:
    container_name: selenoid
    image: aerokube/selenoid:latest-release
    volumes:
      - "/etc/selenoid:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/video:/opt/selenoid/video"
      - "/etc/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/etc/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir",
              "/opt/selenoid/logs", "-limit", "10", "-retry-count", "2",
        "-service-startup-timeout", "2m", "-container-network", "testng-selenoid-ui_selenoid-net"]
    ports:
      - "4444:4444"
    networks:
      - selenoid-net

  selenoid-ui:
    container_name: selenoid_ui
    image: aerokube/selenoid-ui:latest
    links:
      - selenoid
    depends_on:
      - selenoid
    ports:
      - "8083:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    networks:
      - selenoid-net

networks:
  selenoid-net:
    driver: bridge