name: Selenoid + script on container

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout the latest code
      uses: actions/checkout@v3

    - name: Docker cache
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - name: copy browsers.json
      run: sudo mkdir -p /etc/selenoid && sudo cp -R browsers.json /etc/selenoid/.

    - name: download the chrome image
      run: sudo docker pull selenoid/chrome:112.0

    - name: start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: check the container status - default
      run: |
        curl -s http://localhost:4444/status
        curl -s http://localhost:4444/wd/hub

    - name: check the running container
      run: docker ps -a && docker logs selenoid


    - name: Kick start the test via separate container
      run: docker-compose -f "docker-compose-tests.yml" up -d --build

    - name: Stop containers
      if: always()
      run: |
        docker wait testng-selenoid-ui
        docker logs testng-selenoid-ui
        docker rm testng-selenoid-ui
        docker-compose -f "docker-compose.yml" down
        docker-compose -f "docker-compose-tests.yml" down

   
