name: Parallel execution

on:

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout the latest code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: download the chrome image
      run: docker pull selenoid/chrome:112.0

    - name: start containers
      run: docker-compose -f "docker-compose.yml" up -d --build
        
    - name: Build with Maven
      run: mvn -B test --file pom.xml

  -   name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down

   
