name: Zalenium

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout the latest code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Restore Maven cache
      uses: skjolber/maven-cache-github-action@v1
      continue-on-error: true
      with:
        step: restore

    - name: Docker cache
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

   # - name: start containers
    #  run: docker-compose -f "docker-compose-zalenium.yml" up -d --build

    - name: Spin up the zalenium
        uses: ajinx/zalenium@1.1

    - name: Build with Maven
      run: mvn -B test --file pom.xml -Dgrid-url=http://localhost:4444/wd/hub

    - name: Save Maven cache
      uses: skjolber/maven-cache-github-action@v1
      continue-on-error: true
      with:
        step: save

    #- name: Stop containers
    #  if: always()
    #  run: docker logs zalenium && docker-compose -f "docker-compose-zalenium.yml" down

   
